version: '3'

services:
  check-in:
    image: florentfauchille/check-in:v2
    container_name: check-in
    labels:
      traefik.docker.network: "web"
      traefik.enable: "true"
      traefik.http.routers.check-in.rule: "Host(`check-in.groupXX.socra-sigl.fr`)"
      traefik.http.routers.check-in.tls: "true"
      traefik.http.routers.check-in.tls.certresolver: "myresolver"
    networks:
      - web
networks:
  web:
    external: true

